version: "3"

networks:
  seq-net:

volumes:
  seq-data:

services:
  sqelf:
    image: datalust/sqelf:latest
    depends_on:
      - seq
    networks:
      - seq-net
    ports:
      - "12201:12201/udp"
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    restart: unless-stopped
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    networks:
      - seq-net
    environment:
      ACCEPT_EULA: Y
    restart: unless-stopped
    volumes:
      - seq-data:/data